language: python
python:
    - "2.7"
    - "3.2"
    - "2.6"
install:
    # borrowed from https://github.com/facebook/tornado/blob/master/.travis.yml
    # always install unittest2 on py26
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install -r requirements.txt --use-mirrors
script: nosetests tests

