language: python
python:
    - "2.7"
    - "3.2"
    - "2.6"
    #- "3.3"    # lxml-2.3 is not supported in Python 3
env:
    - LXML_VERSION=lxml-2.3
    - LXML_VERSION=lxml-3.0
    - LXML_VERSION=lxml-3.1
    - LXML_VERSION=lxml-latest
install:
    # borrowed from https://github.com/facebook/tornado/blob/master/.travis.yml
    # always install unittest2 on py26
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - pip install -r requirements-$LXML_VERSION.txt --use-mirrors
script: nosetests tests

